parameters:
#    soften_web.example.class: Soften\WebBundle\Example

services:
#    soften_web.example:
#        class: %soften_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
